"""updated the scoring tables

Revision ID: f1fb8050cc98
Revises: 
Create Date: 2023-06-01 20:26:41.215128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1fb8050cc98'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contestants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('contestant_no', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('photo', sa.String(length=80), nullable=True),
    sa.Column('muje_region', sa.String(length=200), nullable=True),
    sa.Column('joined_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contestant_no'),
    sa.UniqueConstraint('title')
    )
    op.create_table('prelimscoring',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('judge', sa.String(length=80), nullable=True),
    sa.Column('contestant_no', sa.Integer(), nullable=True),
    sa.Column('interview', sa.Integer(), nullable=True),
    sa.Column('swimsuit', sa.Integer(), nullable=True),
    sa.Column('ballroom', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=80), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topfivescoring',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('judge', sa.String(length=80), nullable=True),
    sa.Column('contestant_no', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('q_and_a', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topthreescoring',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('judge', sa.String(length=80), nullable=True),
    sa.Column('contestant_no', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('q_and_a', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topthreescoring')
    op.drop_table('topfivescoring')
    op.drop_table('sections')
    op.drop_table('prelimscoring')
    op.drop_table('contestants')
    # ### end Alembic commands ###
